#!/usr/bin/env bash
# Shared helpers for bh-chrome-clone
# shellcheck disable=SC2034

set -euo pipefail

BH_CLONE_ROOT="${BH_CLONE_ROOT:-}"
if [[ -z "${BH_CLONE_ROOT}" ]]; then
  # Resolve project root from this file: lib/common.sh -> repo root
  _COMMON_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  BH_CLONE_ROOT="$(cd "${_COMMON_DIR}/.." && pwd)"
fi

# Defaults (override via env or config/env)
: "${BH_MAIN_PROFILE:=${HOME}/.config/google-chrome}"
: "${BH_CLONE_PROFILE:=${HOME}/.config/browser-harness-chrome-clone}"
: "${BH_CDP_PORT:=9333}"
: "${BH_COOKIE_FILE:=${HOME}/.config/browser-harness/main-cookies.json}"
: "${BH_STATE_DIR:=${HOME}/.config/browser-harness}"
: "${BH_CLONE_LOG:=/tmp/browser-harness-chrome-clone.log}"
: "${BH_ENV_FILE:=${HOME}/.config/browser-harness/env}"
: "${BH_CDP_URL:=http://127.0.0.1:${BH_CDP_PORT}}"
: "${PATH:=${PATH}}"
# Comma-separated domain suffixes never synced (Google account safety by default).
# Override with BH_EXCLUDE_DOMAINS; set BH_INCLUDE_GOOGLE=1 to disable Google blocklist.
: "${BH_EXCLUDE_DOMAINS:=}"
: "${BH_INCLUDE_GOOGLE:=0}"

# Prefer user-local tools
export PATH="${HOME}/.local/bin:${PATH}"

log()  { printf '%s\n' "$*"; }
info() { printf '[bh-clone] %s\n' "$*"; }
warn() { printf '[bh-clone] WARN: %s\n' "$*" >&2; }
die()  { printf '[bh-clone] ERROR: %s\n' "$*" >&2; exit 1; }

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "missing required command: $1"
}

load_user_env() {
  if [[ -f "${BH_ENV_FILE}" ]]; then
    # shellcheck disable=SC1090
    source "${BH_ENV_FILE}" || true
  fi
}

ensure_state_dir() {
  mkdir -p "${BH_STATE_DIR}"
  chmod 700 "${BH_STATE_DIR}" 2>/dev/null || true
}

cdp_ready() {
  local port="${1:-${BH_CDP_PORT}}"
  curl -sS --max-time 1 "http://127.0.0.1:${port}/json/version" >/dev/null 2>&1
}

wait_cdp() {
  local port="${1:-${BH_CDP_PORT}}"
  local tries="${2:-40}"
  local i
  for i in $(seq 1 "${tries}"); do
    if cdp_ready "${port}"; then
      return 0
    fi
    sleep 1
  done
  return 1
}

require_browser_harness() {
  require_cmd browser-harness
  require_cmd curl
  require_cmd google-chrome || require_cmd chromium || true
  if ! command -v google-chrome >/dev/null 2>&1 && ! command -v chromium >/dev/null 2>&1; then
    die "google-chrome or chromium not found in PATH"
  fi
}

chrome_bin() {
  if command -v google-chrome >/dev/null 2>&1; then
    command -v google-chrome
  elif command -v google-chrome-stable >/dev/null 2>&1; then
    command -v google-chrome-stable
  elif command -v chromium >/dev/null 2>&1; then
    command -v chromium
  else
    die "Chrome/Chromium binary not found"
  fi
}

write_env_clone() {
  ensure_state_dir
  cat > "${BH_ENV_FILE}" <<EOF
# Generated by bh-chrome-clone — automation clone mode
export PATH="\${HOME}/.local/bin:\${PATH}"
export BU_CDP_URL=http://127.0.0.1:${BH_CDP_PORT}
export BH_CDP_PORT=${BH_CDP_PORT}
export BH_CLONE_PROFILE="${BH_CLONE_PROFILE}"
export BH_COOKIE_FILE="${BH_COOKIE_FILE}"
EOF
}

write_env_main() {
  ensure_state_dir
  cat > "${BH_ENV_FILE}" <<'EOF'
# Generated by bh-chrome-clone — main Chrome mode
export PATH="${HOME}/.local/bin:${PATH}"
unset BU_CDP_URL
unset BU_CDP_WS
EOF
}

strip_clone_locks() {
  local profile="${1:-${BH_CLONE_PROFILE}}"
  find "${profile}" -maxdepth 2 \( \
    -name 'Singleton*' -o -name 'lockfile' -o -name 'RunningChromeVersion' \
  \) -delete 2>/dev/null || true
}

enable_remote_debugging_pref() {
  local profile="${1:-${BH_CLONE_PROFILE}}"
  local state="${profile}/Local State"
  [[ -f "${state}" ]] || return 0
  python3 - "${state}" <<'PY'
import json, sys
from pathlib import Path
p = Path(sys.argv[1])
data = json.loads(p.read_text(encoding="utf-8", errors="replace"))
data.setdefault("devtools", {}).setdefault("remote_debugging", {})["user-enabled"] = True
p.write_text(json.dumps(data, ensure_ascii=False), encoding="utf-8")
PY
}

kill_clone_chrome() {
  local profile="${BH_CLONE_PROFILE}"
  local port="${BH_CDP_PORT}"
  # Kill by user-data-dir match (avoid -f pkill self-match patterns in wrappers)
  local pids
  pids="$(pgrep -f "user-data-dir=${profile}" 2>/dev/null || true)"
  if [[ -n "${pids}" ]]; then
    # shellcheck disable=SC2086
    kill ${pids} 2>/dev/null || true
    sleep 1
  fi
  # Best-effort free port
  if command -v fuser >/dev/null 2>&1; then
    fuser -k "${port}/tcp" 2>/dev/null || true
  fi
}
